name: fold_button
version: 1.2.1
author: Keiichiro Ui <keiichiro.ui@gmail.com>
description: A custom element to fold/unfold the element specified with the <code>target</code> attribute.
homepage: https://github.com/kui/fold_button
environment:
  sdk: '>=1.11.0'
dependencies:
  polymer: '>=0.16.0 <0.17.0'
dev_dependencies:
  ghpages_generator: '>=0.3.0 <0.4.0'
transformers:
- polymer:
    entry_points:
    - example/index.html
